version: 0.2


phases:
  pre_build:
    commands:
      - npm install
      - pip install --user aws-sam-cli  
      

  build:
    commands:
 
      - sam build 
      - yes | sam deploy

 
  post_build:
    commands:
  
