version: 0.2


phases:
  pre_build:
    commands:
      - npm install
      - npm install
      - pip install --user aws-sam-cli  
      - USER_BASE_PATH=$(python -m site --user-base)
      - export PATH=$PATH:$USER_BASE_PATH/bin
  

  build:
    commands:
      - sam package --template-file template.yaml --s3-bucket mvpsamcf --output-template-file out.yaml
 
      - sam build 
        

  post_build:
    commands:
      - echo y | sam deploy
      - aws s3 sync ./ s3://mvpsamcf --acl public-read --delete


  
