version: 0.2


phases:
  pre_build:
    commands:
      - npm install
      - pip install --user aws-sam-cli  
      - USER_BASE_PATH=$(python -m site --user-base)
      - export PATH=$PATH:$USER_BASE_PATH/bin
      - sam build 

  build:
    commands:
      
      - printf 'samuel-app\neu-central-1/nsimplechat_connections/nY' | sam deploy --guided

 
  post_build:
    commands:
  
