version: 0.2


phases:
  pre_build:
    commands:
      - npm install
      - pip install --user aws-sam-cli  
      

  build:
    commands:
      - USER_BASE_PATH=$(python -m site --user-base)
      - export PATH=$PATH:$USER_BASE_PATH/bin
      - sam build 
      - sam deploy --confirm-changeset
 
  post_build:
    commands:
      - echo $AWS_ACCESS_ID
      - printf '{"ImageURI":"image_URI"}' > imageDetail.json
