AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'mvp-sam

  SAM Template for mvp-sam

  '
Globals:
  Function:
    Timeout: 3
Parameters:
  TableName:
    Type: String
    Default: mvpchatlog
    Description: (Required) The name of the new DynamoDB to store connection identifiers
      for each connected clients. Minimum 3 characters
    MinLength: 3
    MaxLength: 50
    AllowedPattern: ^[A-Za-z_]+$
    ConstraintDescription: Required. Can be characters and underscore only. No numbers
      or special characters allowed.
  TableNamea:
    Type: String
    Default: mvpusers
    Description: (Required) The name of the new DynamoDB to store connection identifiers
      for each connected clients. Minimum 3 characters
    MinLength: 3
    MaxLength: 50
    AllowedPattern: ^[A-Za-z_]+$
    ConstraintDescription: Required. Can be characters and underscore only. No numbers
      or special characters allowed.
  TableNameb:
    Type: String
    Default: simplechatconnections
    Description: (Required) The name of the new DynamoDB to store connection identifiers
      for each connected clients. Minimum 3 characters
    MinLength: 3
    MaxLength: 50
    AllowedPattern: ^[A-Za-z_]+$
    ConstraintDescription: Required. Can be characters and underscore only. No numbers
      or special characters allowed.
  TableNamec:
    Type: String
    Default: simplechatconnectionssss
    Description: (Required) The name of the new DynamoDB to store connection identifiers
      for each connected clients. Minimum 3 characters
    MinLength: 3
    MaxLength: 50
    AllowedPattern: ^[A-Za-z_]+$
    ConstraintDescription: Required. Can be characters and underscore only. No numbers
      or special characters allowed.
Resources:
  mvpsocket:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: mvpsocket
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: $request.body.message
  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: mvpsocket
      RouteKey: $connect
      AuthorizationType: NONE
      OperationName: ConnectRoute
      Target:
        Fn::Join:
        - /
        - - integrations
          - Ref: ConnectInteg
  ConnectInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId:
        Ref: mvpsocket
      Description: Connect Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OnConnectFunction.Arn}/invocations
  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: mvpsocket
      RouteKey: $disconnect
      AuthorizationType: NONE
      OperationName: DisconnectRoute
      Target:
        Fn::Join:
        - /
        - - integrations
          - Ref: DisconnectInteg
  DisconnectInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId:
        Ref: mvpsocket
      Description: Disconnect Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OnDisconnectFunction.Arn}/invocations
  SendRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: mvpsocket
      RouteKey: sendmessage
      AuthorizationType: NONE
      OperationName: SendRoute
      Target:
        Fn::Join:
        - /
        - - integrations
          - Ref: SendInteg
  SendInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId:
        Ref: mvpsocket
      Description: Send Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SendMessageFunction.Arn}/invocations
  Deployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
    - ConnectRoute
    - SendRoute
    - DisconnectRoute
    Properties:
      ApiId:
        Ref: mvpsocket
  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: Prod
      Description: Prod Stage
      DeploymentId:
        Ref: Deployment
      ApiId:
        Ref: mvpsocket
  mvpchatlog:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Ref: TableName
      AttributeDefinitions:
      - AttributeName: date
        AttributeType: N
      KeySchema:
      - AttributeName: date
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: true
  mvpusers:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Ref: TableNamea
      AttributeDefinitions:
      - AttributeName: date
        AttributeType: N
      KeySchema:
      - AttributeName: date
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: true
  ConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: connectionId
        AttributeType: S
      KeySchema:
      - AttributeName: connectionId
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: true
      TableName:
        Ref: TableNameb
  OnConnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mvpsamcloudformation/e9cf27f12b34ecb8f8199c8a9ec931ad
      Handler: app.handler
      MemorySize: 256
      Runtime: nodejs12.x
      Environment:
        Variables:
          TABLE_NAME:
            Ref: TableName
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TableNamec
  OnConnectPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
    - mvpsocket
    - OnConnectFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: OnConnectFunction
      Principal: apigateway.amazonaws.com
  OnDisconnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mvpsamcloudformation/9cff5fd5fd3599e9ccc85588482eb173
      Handler: app.handler
      MemorySize: 256
      Runtime: nodejs12.x
      Environment:
        Variables:
          TABLE_NAME:
            Ref: TableName
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TableName
  OnDisconnectPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
    - mvpsocket
    - OnDisconnectFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: OnDisconnectFunction
      Principal: apigateway.amazonaws.com
  SendMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mvpsamcloudformation/deba4da244b957b4a0be74a2a76340fc
      Handler: app.handler
      MemorySize: 256
      Runtime: nodejs12.x
      Environment:
        Variables:
          TABLE_NAME:
            Ref: TableName
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TableName
      - Statement:
        - Effect: Allow
          Action:
          - execute-api:ManageConnections
          Resource:
          - Fn::Sub: arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${mvpsocket}/*
  SendMessagePermission:
    Type: AWS::Lambda::Permission
    DependsOn:
    - mvpsocket
    - SendMessageFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: SendMessageFunction
      Principal: apigateway.amazonaws.com
  mvpqr:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mvpqr
  ProductBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: mvpangularsrc
      PolicyDocument:
        Id: PublicReadPolicy
        Version: 2012-10-17
        Statement:
        - Sid: PublicReadForGetBucketObjects
          Effect: Allow
          Principal: '*'
          Action: s3:GetObject
          Resource:
            Fn::Sub: arn:aws:s3:::${mvpangularsrc}/*
  mvpsrc:
    Type: AWS::S3::Bucket
  ProductBucketPolicy2:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: mvpsamsrc
      PolicyDocument:
        Id: PublicReadPolicy
        Version: 2012-10-17
        Statement:
        - Sid: PublicReadForGetBucketObjects
          Effect: Allow
          Principal: '*'
          Action: s3:GetObject
          Resource:
            Fn::Sub: arn:aws:s3:::${mvpsamsrc}/*
  mvpangular:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mvpangular
  mvpsamsrc:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mvpsamsrc
  mvpangularsrc:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mvpangularsrc
  myLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: myLogGroup
      RetentionInDays: 180
  myLogStream:
    Type: AWS::Logs::LogStream
    Properties:
      LogGroupName:
        Ref: myLogGroup
      LogStreamName: myLogStream
  createTableLog:
    Type: AWS::Logs::LogGroup
    DependsOn:
    - createTable
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${createTable}
      RetentionInDays: 7
  addToKitchenLogLog:
    Type: AWS::Logs::LogGroup
    DependsOn:
    - addToKitchenLog
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${addToKitchenLog}
      RetentionInDays: 7
  createUserLog:
    Type: AWS::Logs::LogGroup
    DependsOn:
    - createUser
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${createUser}
      RetentionInDays: 7
  mvpuserpool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: mvpuserpool
  addToCustomerLog:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mvpsamcloudformation/60b8119dc33c2db90ccb94a32e568599
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /addtocustomerlogs
            Method: get
      Policies:
      - AmazonDynamoDBFullAccess
      - AmazonS3FullAccess
  addToAdminLog:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mvpsamcloudformation/572414195df5f70e8b5e83dfe493c6f1
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /addtoadminlogs
            Method: get
      Policies:
      - AmazonDynamoDBFullAccess
      - AmazonS3FullAccess
  addToKitchenLog:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mvpsamcloudformation/e65c245e63d07fcd7b9c90a036e8a4c9
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /addtokitchenlogs
            Method: get
      Policies:
      - AmazonDynamoDBFullAccess
  createUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mvpsamcloudformation/9f87c0045a35cf061915733b28a8b619
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /createuser
            Method: get
      Policies:
      - AmazonDynamoDBFullAccess
  createTable:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mvpsamcloudformation/60444ab09c31b18b41b7348eb11df217
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /createtable
            Method: get
      Policies:
      - AmazonDynamoDBFullAccess
  storeQr:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mvpsamcloudformation/90537e1807cfe63096b29461b81db3f5
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /storeqr
            Method: get
      Policies:
      - AmazonS3FullAccess
Outputs:
  addToCustomerLogApi:
    Description: API Gateway endpoint URL for Prod stage for addToCustomerLog function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/
  addToCustomerLog:
    Description: addtoCustomerLog Lambda Function ARN
    Value:
      Fn::GetAtt:
      - addToCustomerLog
      - Arn
  addToCustomerLogIamRole:
    Description: Implicit IAM Role created for addToCustomerLogfunction
    Value:
      Fn::GetAtt:
      - addToCustomerLogRole
      - Arn
  addToAdminLogApi:
    Description: API Gateway endpoint URL for Prod stage for addToAdminLogRole function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/
  addToAdminLog:
    Description: addToAdminLogRole Lambda Function ARN
    Value:
      Fn::GetAtt:
      - addToAdminLog
      - Arn
  addToAdminLogIamRole:
    Description: Implicit IAM Role created for addToAdminLogRole function
    Value:
      Fn::GetAtt:
      - addToAdminLogRole
      - Arn
  addToKitchenLogApi:
    Description: API Gateway endpoint URL for Prod stage for addToKitchenLog function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/
  addToKitchenLog:
    Description: addToKitchenLog Lambda Function ARN
    Value:
      Fn::GetAtt:
      - addToKitchenLog
      - Arn
  addToKitchenLogIamRole:
    Description: Implicit IAM Role created for addToKitchenLog function
    Value:
      Fn::GetAtt:
      - addToKitchenLogRole
      - Arn
  createUserApi:
    Description: API Gateway endpoint URL for Prod stage for createUser function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/
  createUser:
    Description: createUser Lambda Function ARN
    Value:
      Fn::GetAtt:
      - createUser
      - Arn
  createUserIamRole:
    Description: Implicit IAM Role created for createUser function
    Value:
      Fn::GetAtt:
      - createUserRole
      - Arn
  createTableApi:
    Description: API Gateway endpoint URL for Prod stage for createTable function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/
  createTable:
    Description: createTable Lambda Function ARN
    Value:
      Fn::GetAtt:
      - createTable
      - Arn
  createTableIamRole:
    Description: Implicit IAM Role created for createTab;e function
    Value:
      Fn::GetAtt:
      - createTableRole
      - Arn
  storeQrApi:
    Description: storeQr endpoint URL for Prod stage for storeQrfunction
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/
  storeQr:
    Description: storeQr Lambda Function ARN
    Value:
      Fn::GetAtt:
      - storeQr
      - Arn
  storeQrIamRole:
    Description: Implicit IAM Role created for storeQr function
    Value:
      Fn::GetAtt:
      - storeQrRole
      - Arn
