version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mvp-sam"
s3_bucket = "mvpsamcloudformation"
s3_prefix = "mvp" 
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

